name: minimal_alarm
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  rxdart: ^0.23.1
  json_annotation: ^3.0.1
  shared_preferences: ^0.5.6+3
  flutter_screenutil: ^1.1.0
  transformer_page_view: ^0.1.6
  cupertino_icons: ^0.1.3
  numberpicker: ^1.2.0
  intl: ^0.16.0
  mobx_codegen: ^1.0.3
  flutter_mobx: ^1.1.0
  google_fonts: ^0.4.0
  path_provider: ^1.6.5
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  arcore_flutter_plugin: ^0.0.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl_translation:
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/locale/localization_en.json
    - lib/assets/locale/localization_ru.json

#    - lib/assets/images/back.png
#  fonts:
#    - family: Khula
#      fonts:
#        - asset: lib/assets/fonts/khula-light.otf
#          weight: 300
#          style: normal
#        - asset: lib/assets/fonts/khula-regular.otf
#          weight: 400
#          style: normal
#        - asset: lib/assets/fonts/khula-semibold.otf
#          weight: 500
#          style: normal
#        - asset: lib/assets/fonts/khula-bold.otf
#          weight: 600
#          style: normal
#        - asset: lib/assets/fonts/khula-extrabold.otf
#          weight: 700
#          style: normal