name: cv_profile
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.0.2
  flutter_bloc: ^6.0.1
  json_annotation: ^3.0.1
  shared_preferences: ^0.5.8
  flutter_screenutil: ^2.3.1
  cupertino_icons: ^0.1.3
  intl: ^0.16.1
  google_fonts: ^1.1.0
  transparent_image: ^1.0.0
  responsive_framework: ^0.0.8
  flutter_staggered_grid_view: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl_translation:
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/locale/localization_en.json
    - lib/assets/locale/localization_ru.json
    - lib/assets/images/profile_photo.jpg

#  fonts:
#    - family: Khula
#      fonts:
#        - asset: lib/assets/fonts/khula-light.otf
#          weight: 300
#          style: normal
#        - asset: lib/assets/fonts/khula-regular.otf
#          weight: 400
#          style: normal
#        - asset: lib/assets/fonts/khula-semibold.otf
#          weight: 500
#          style: normal
#        - asset: lib/assets/fonts/khula-bold.otf
#          weight: 600
#          style: normal
#        - asset: lib/assets/fonts/khula-extrabold.otf
#          weight: 700
#          style: normal